-- AlterEnum (Add new expense types)
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'INSURANCE';
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'SUPPLIES';
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'MARKETING';
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'MAINTENANCE';
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'TAXES';
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'BANK_FEES';
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'SOFTWARE';
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'PROFESSIONAL';

-- AlterTable (Add new columns to Expense)
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "vendor" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "reference" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "isPaid" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3);
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Expense_locationId_idx" ON "Expense"("locationId");
CREATE INDEX IF NOT EXISTS "Expense_type_idx" ON "Expense"("type");
CREATE INDEX IF NOT EXISTS "Expense_date_idx" ON "Expense"("date");
